sudo: required
services:
  - docker

before_install:
  - docker build -t walkermj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true walkermj/react-test npm test -- --coverage

after_success:
  - docker build -t walkermj/multi-client ./client
  - docker build -t walkermj/multi-nginx ./nginx
  - docker build -t walkermj/multi-server ./server
  - docker build -t walkermj/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to dockerhub
  - docker push walkermj/multi-client
  - docker push walkermj/multi-nginx
  - docker push walkermj/multi-server
  - docker push walkermj/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  environment: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-951344299841
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


